### ISSUE TITLE
Switching to shadowmap causes instant crash

### ISSUE THREAD

**Issue by Reshiram110** [Roblox/future-is-bright#10]
Whenever I try enabling the shadowmap Lighting mode, studio instantly crashes for me. No lag, nothing. Just instantly crashes with the regular crash dialog box.

PC Specs:

Windows 7 64 bit OS
Intel i3 CPU
4GB RAM

**Comment by LouieK22** [comment]
Are there any maps that work fine?

**Comment by Reshiram110** [comment]
None work with shadowmapping. Trying to enable shadowmapping results in an instant crash.

**Comment by LouieK22** [comment]
This might be related to #2 as all cases given including your's use Windows 7.

**Comment by Reshiram110** [comment]
Looks like it.

**Comment by zeux** [comment]
Would you mind:
1) Running prototype Studio build to trigger the crash
2) Going to C:\Users\username\AppData\Local\Roblox\logs
3) Uploading the latest file with _1.txt suffix here?

**Comment by TheSink** [comment]
I know you asked him to do so, but I'm having the same issue so I don't think it would hurt. Here:
[log_47D6B_1.txt](https://github.com/Roblox/future-is-bright/files/1167912/log_47D6B_1.txt)

**Comment by zeux** [comment]
Turns out we actually have crash reporting working on this build and we have a solid number of crashes. I'll look into this on Monday, thanks!

**Comment by hunte922** [comment]
Try turning on GlobalShadows before enabling ShadowMap.

**Comment by BrainDamaged0** [comment]
u must have powerfuel PC to use the shadowmap which i have and even more powerfuel PC u have still it crashes which that problem must sovle the roblox, and i have powerfuel PC and i can run (Example) Battlefield 4 and why i can't test the prototy shadowmap which for me makes no sences or thats once aigen roblox problem. 

My PC:
Windows 7 Home Premium 64-bit SP1
AMD Athlom(tm) II X2 250 Processor 3.0 (which i am gona buy new) c:
RAM:8
NVDIA Geforce GTX 650 Ti

**Comment by zeux** [comment]
Fixed in v2; you can download the new build from https://github.com/Roblox/future-is-bright/releases

**Comment by BrainDamaged0** [comment]
why the shadowmap is different than VoxelGPUCascaded.. bec VoxelGPUCascaded haves pretty graphics but shadowmap ist not the same it was the v1.
