### ISSUE TITLE
v13 - Weird unexplainable shadow

### ISSUE THREAD

**Issue by EtheriousRaiden** [Roblox/future-is-bright#103]
Images : 

https://i.imgur.com/XGSJRz5.png
https://i.imgur.com/DJbowhM.jpg
https://i.imgur.com/PKSX6tS.jpg
https://i.imgur.com/pHPxvqH.jpg

I just got FiB v13 today, and I don't know what is going on so lol.

**Comment by zeux** [comment]
I'm assuming this is fixed in v15; if it's still a problem, feel free to open a new issue with a repro level.
