### ISSUE TITLE
random static appearing V13

### ISSUE THREAD

**Issue by editedreality** [Roblox/future-is-bright#105]
as far as i can tell it only happens near a wall with a light source it doesent need to be a corner tho but thats how i got the screenshot
![image](https://user-images.githubusercontent.com/37640997/41123340-39ecfd8c-6a96-11e8-8d6c-9a861d287925.png)
edit: looks like the static is the shadows?

**Comment by zeux** [comment]
We fixed something like this in v14 I think; v15 should work now.
