### ISSUE TITLE
v13 crashing upon place loading

### ISSUE THREAD

**Issue by coolguy5343333** [Roblox/future-is-bright#107]
Hi! 'Roblox has encountered an error and needs to quit, sorry!' before I can get into a place at all. tried running as admin, restarting, etc. running from the folder on the computer - not the zip.

Thanks

**Comment by DamnMerc** [comment]
I don't exactly have much of a answer for this, but posting the crash log may help.

**Comment by coolguy5343333** [comment]
Please could you tell me where to find the crash log?

Thanks

**Comment by DamnMerc** [comment]
C:\Users\User\AppData\Local\Roblox\crashlogs

**Comment by Hifiveghost5** [comment]
heres my crash log:
"1537922235.03381,42d4,6 CrashReporter Start
1537922235.03381,4048,6 WatcherThread Started
1537922235.03481,42d4,6 Uploading 4 crashes to Roblox crash analyzer
1537922235.03481,42d4,6 Uploading C:\Users\Hifiveghost5\AppData\Local\Roblox\logs\log_05FCE 0, 0, 0, 219135.RobloxStudio.dmp
1537965455.90234,42d4,6 Exception when uploading dump(s): CURL error (curl_easy_perform): Timeout was reached (28)
1537965458.34375,42d4,6 Uploading C:\Users\Hifiveghost5\AppData\Local\Roblox\logs\log_11976 0, 0, 0, 219135.RobloxStudio.dmp
1537965460.43750,42d4,6 Exception when uploading dump(s): CURL error (curl_easy_perform): Couldn't resolve host name (6)
1537965460.44141,42d4,6 Uploading C:\Users\Hifiveghost5\AppData\Local\Roblox\logs\log_16B02 0, 0, 0, 219135.RobloxStudio.dmp
1537965461.93750,42d4,6 Exception when uploading dump(s): CURL error (curl_easy_perform): Couldn't resolve host name (6)
1537965461.93750,42d4,6 Uploading C:\Users\Hifiveghost5\AppData\Local\Roblox\logs\log_F563F.ini
1537965461.95313,42d4,6 Exception when uploading dump(s): CURL error (curl_easy_perform): Couldn't resolve host name (6)
1537965461.95313,42d4,6 Uploading C:\Users\Hifiveghost5\AppData\Local\Roblox\logs\log_F563F_1.txt
1537965462.01172,42d4,6 Exception when uploading dump(s): CURL error (curl_easy_perform): Couldn't resolve host name (6)"

**Comment by zeux** [comment]
This should be fixed in v15, feel free to open a new issue if it still happens.
