### ISSUE TITLE
How do I set it up??

### ISSUE THREAD

**Issue by matthewwilson25** [Roblox/future-is-bright#11]
Seriously.. How? xD

**Comment by LouieK22** [comment]
Download the release from this link: https://github.com/Roblox/future-is-bright/releases/download/v1/future-is-bright-v1.zip

Unzip it like you would any other zip and then navigate inside the folder and launch RobloxStudioBeta.exe. Now, open a normal studio template, I recommend western. Once the template has opened you'll want to change a property under Lighting called "LightingMode", set that to "ShadowMap". And you're done, you have the new lighting.

**Comment by matthewwilson25** [comment]
What do you mean Navigate?

**Comment by LouieK22** [comment]
Depending on where you unzipped the release, you'll want to double click on the folder to go into it, then just continue with the instructions I gave above.

**Comment by matthewwilson25** [comment]
Got it, thanks.

**Comment by LouieK22** [comment]
Glad I could help. If all your problems are solved, then it would be best to close the issue.
