### ISSUE TITLE
Shadows not working.

### ISSUE THREAD

**Issue by BluSpectrum** [Roblox/future-is-bright#113]
Whenever you use something like a point light or surface light, shadows simply don't work even when you have the "Shadows" option ticked. Global shadows work though, and I do have Future is Bright enabled.
Here's a screenshot of whats happening
![image](https://user-images.githubusercontent.com/40967759/42424621-27664bdc-82dd-11e8-9a8f-68ed3b0eac16.png)

**Comment by DamnMerc** [comment]
Could you drop a repo of the place?
Pointlight: 
![image](https://user-images.githubusercontent.com/8603387/42726244-28ccf36e-875f-11e8-9119-cc2cdce90479.png)
As far as I know, surface lights are the only light instance to not cast any shows or respect a part.
![image](https://user-images.githubusercontent.com/8603387/42726257-8218aabc-875f-11e8-92f7-e4da4ffac2c6.png)

**Comment by zeux** [comment]
I'm assuming this is fixed in v15; if it isn't, please open another issue with a repro level and PC/Mac specs.
