### ISSUE TITLE
Terrain Material Colors Disappeared In Future Is Bright v11

### ISSUE THREAD

**Issue by UnsatisfiedPrius** [Roblox/future-is-bright#117]
I've been using this Future Is Bright version 11 for a while now as I prefer the simple VoxelGPUCascaded and ShadowMap options and seemingly unlimited rendering distance of the shaders over what was brought to the table in the hybrid technology. However, recently the material colors option has disappeared from the terrain properties menu. I have tried everything from redownloading v11, to trying all previous versions, to messing with FFlags to no form of success whatsoever. 

I tried getting used to the newest version, but the lighting just doesn't look the same as it did before, and I noticed that a lot of my projects that would have previously ran at a steady 60 FPS are now uneditable from extreme amounts of lag, and it feels very counterproductive to downgrade the scenic visuals of my projects that I've spent months working on.

Posting this here may be my only hope of getting some sort of solution to this problem. I am not a member of the developer forum, so I am unable to seek help there. A friend of mine tried posting my issue there, but their thread was locked and they were told not to post on the behalf of others. I tried seeking help on the unofficial ROBLOX subreddit, but was only told to reinstall which didn't even solve the problem.
Edit: I noticed Future Is Bright 12 has this issue as well even though it's running on the hybrid engine.
![broken](https://user-images.githubusercontent.com/42261094/43939865-41bc1494-9c32-11e8-8235-b5fd391a41a6.PNG)

EDIT: When searching through the properties menu, the MaterialColors option appears, but it doesn't do anything.
![image](https://user-images.githubusercontent.com/42261094/44009160-4d00138e-9e6f-11e8-9b1f-f24de463c65e.png)

**Comment by UnsatisfiedPrius** [comment]
It was working before. I don't know how it just randomly stopped working one day.

**Comment by donkeyrat** [comment]
Why don't you use v14?

**Comment by UnsatisfiedPrius** [comment]
The shading doesn't look as good to me, and many of my projects are so laggy in v14 that they're unusable unless I completely downgrade the shading. It just doesn't look good only having nearby objects be affected by shadows.

**Comment by UnsatisfiedPrius** [comment]
The glass texture just randomly stopped working now.

**Comment by donkeyrat** [comment]
All versions are currently broken until they update.

**Comment by UnsatisfiedPrius** [comment]
I hope the update fixes my problems rather than adds more.

**Comment by zeux** [comment]
We're not going to update v11 anymore. If you have places that are slow with new versions, feel free to file a separate bug for performance investigation. Same goes for quality. I'll close this for now.
