### ISSUE TITLE
Everything is Broken

### ISSUE THREAD

**Issue by donkeyrat** [Roblox/future-is-bright#119]
As of recently, most things in studio are broken.
![image](https://user-images.githubusercontent.com/41966410/44543987-f260d300-a6c5-11e8-821f-e6667cfa8021.png) Most images in studio aren't appearing. The custom plugins have images, and the built in ones dont. 
![image](https://user-images.githubusercontent.com/41966410/44544036-0e647480-a6c6-11e8-8339-0caaf23963f5.png) 
![image](https://user-images.githubusercontent.com/41966410/44544045-12909200-a6c6-11e8-9ba0-97b19d964fa0.png) Also, the terrain editor is very broken. 
![image](https://user-images.githubusercontent.com/41966410/44544069-22a87180-a6c6-11e8-978d-cb84162551f9.png) We need v15 asap.

**Comment by donkeyrat** [comment]
Also, when i hover my cursor over things, it doesn't show the icon where i can click on it.

**Comment by zeux** [comment]
Fixed in v15
