### ISSUE TITLE
DOESN'T EVEN LOAD THE GRAPHICS

### ISSUE THREAD

**Issue by qu47** [Roblox/future-is-bright#12]
It just loads the current screen

**Comment by zeux** [comment]
Would you mind:

1) Running prototype Studio build to trigger the issue
2) Going to C:\Users\username\AppData\Local\Roblox\logs
3) Uploading the latest file with _1.txt suffix here?

**Comment by qu47** [comment]
[log_EE507_1.txt](https://github.com/Roblox/future-is-bright/files/1168262/log_EE507_1.txt)

**Comment by zeux** [comment]
Looks like your GPU supports Direct3D 10 but not Direct3D11 which is currently required by this prototype build. I will update the build to clearly indicate this is the case.

**Comment by qu47** [comment]
Is there any way I can manually install D3D11 on it

**Comment by neopy2** [comment]
I have DX12 but I am having the same issue?

**Comment by Jody7** [comment]
"It requires Windows 7 (or higher) and a mid-tier DirectX 11 compatible GPU"

I don't believe that integrated graphics is a "mid-tier GPU"

**Comment by neopy2** [comment]
I saw that someone else can use it but they have the intel integrated graphics

**Comment by zeux** [comment]
There were a few other reasons that could cause this (such as changing the GraphicsMode...) - the new build which you can download the new build from https://github.com/Roblox/future-is-bright/releases should either work or clearly indicate that your system is currently incompatible.
