### ISSUE TITLE
Older versions of FIB (below v14) would use SystemMenu when the Ribbon Bar is selected in settings

### ISSUE THREAD

**Issue by xCoderJay** [Roblox/future-is-bright#121]

**Comment by UnsatisfiedPrius** [comment]
Ribbon bar is still working for me on v11

**Comment by xCoderJay** [comment]
@UnsatisfiedPrius Yes, it works on older versions, but suprisingly not a newer version.

**Comment by zeux** [comment]
This should be fixed in v15 - assuming that v14 didn't work for you because of crashes.
