### ISSUE TITLE
Whenever your not having your cursor over an object the box doesn't appear like it should in the normal Studio

### ISSUE THREAD

**Issue by xCoderJay** [Roblox/future-is-bright#122]

**Comment by xCoderJay** [comment]
I'll add some pictures dw

**Comment by donkeyrat** [comment]
I believe the problem is the studio version is broken and the proper images are not working. This has been happening and the built in images on studio arent showing up.

**Comment by zeux** [comment]
Cursors seem to work in v15, closing this.
