### ISSUE TITLE
Glass is black

### ISSUE THREAD

**Issue by BluSpectrum** [Roblox/future-is-bright#124]
The title describes my problem. I've tried reinstalling Studio but that doesn't help.

Here's an example:
![image](https://user-images.githubusercontent.com/40967759/45329576-137f4b80-b52f-11e8-9cb7-38d67e55e6bb.png)

I've noticed this is very similar to how glass looks when you set its reflectance to inf.

Thanks!

**Comment by donkeyrat** [comment]
ATM, I highly recommend to not use future is bright. It is very glitchy and broken, so I'd suggest to wait until the next version.

**Comment by UnsatisfiedPrius** [comment]
On v11 it's not black, but refuses to even use the texture instead. It looks identical to smooth plastic.

**Comment by zeux** [comment]
Fixed in v15
