### ISSUE TITLE
Shadow flickering + reflection issues

### ISSUE THREAD

**Issue by CaptainPaperHat** [Roblox/future-is-bright#126]
This version of the prototype breaks reflections and breaks shadows.
1. The glass material doesn't seem to reflect the skybox, as it should be
![reflection problem](https://user-images.githubusercontent.com/33442219/45604703-e2e65880-b9eb-11e8-9ae6-e276983e764c.gif)
2. The shadow flickering happens nonstop, in both testing mode and editing mode (the flickering is lessened while testing). Changing the HybridBlendDist doesn't seem to do anything either..
![shadow problem](https://user-images.githubusercontent.com/33442219/45604808-df070600-b9ec-11e8-9893-4bf9d96843a8.gif)

**Comment by zeux** [comment]
Glass is fixed in v15. I'm not 100% sure about the flickering - I think we fixed a bug that looked pretty much like this though. So try v15, and feel free to create a new issue if it's still broken.

**Comment by CaptainPaperHat** [comment]
> Glass is fixed in v15. I'm not 100% sure about the flickering - I think we fixed a bug that looked pretty much like this though. So try v15, and feel free to create a new issue if it's still broken.

The new version actually fixes the shadow flickering completely. Thanks for the hard work on this project!
