### ISSUE TITLE
Artifacts with surface lights and ShadowMap type lighting

### ISSUE THREAD

**Issue by Knightshade** [Roblox/future-is-bright#13]
I've posted a picture as an example. There's strange artifacts like "cuts" in the light casted upon. In this example I have a surface light on each surface except for the ends with shadows enabled and and angle kept at 90.

![oddbug](https://user-images.githubusercontent.com/6109240/28496166-32e8a5bc-6f2a-11e7-99d0-4ec952d70ebf.png)

**Comment by Knightshade** [comment]
Here's specs since I forgot to add them
AMD R7 1700X OC'd @ 3.8GHz
16.0GB RAM @ 2400Mhz
Strix 1080 @ stock clock
Win 10 Pro 64 Bit

**Comment by hunte922** [comment]
![screenshot_107](https://user-images.githubusercontent.com/5272529/28496964-125af352-6f40-11e7-8e2b-3e25a6687dd9.png)
Got the same issue on this particular ceiling, but worse. [Here is an RBXL for repro.](https://www.mediafire.com/?4c4gt1idrwwb751)

**Comment by zeux** [comment]
@hunte922 I only see SpotLight objects in the level you attached - are you sure it's the right one?

@Knightshade Can you post the level that you are having issues with?

**Comment by Knightshade** [comment]
I don't think I had saved that level. I'll try to reproduce it with v2.

**Comment by zeux** [comment]
Closing this for now since I fixed an issue like this in v3, feel free to reopen if you find a repro that's still broken.
