### ISSUE TITLE
camera won't move in run mode

### ISSUE THREAD

**Issue by adasgadfg** [Roblox/future-is-bright#131]
when in run mode if the mouse is in the view port it disappears and right click does not work, selecting objects through the viewport still works properly using v15, there aren't any errors in the output
![image](https://user-images.githubusercontent.com/43719546/46255629-f1cb1180-c4a7-11e8-82f4-bd9fdfaae38b.png)

**Comment by marcuss95** [comment]
wierd, mine doesnt let me run, play, and others it would get stuck at 33%

**Comment by zeux** [comment]
Should be fixed in v16.
