### ISSUE TITLE
LightingMode wont show up

### ISSUE THREAD

**Issue by TheLifeOfTheePie** [Roblox/future-is-bright#133]
When using the Future is Bright, i get no option saying lighting mode. Future is bright is activated and im using a Mac. BUT   idk if im on the RIght version, i downloaded the latest on GitHub, but mabye i just need a GameTest2 or whatever the latest GameTest is, also WERE do we get GameTest? thx!

**Comment by adasgadfg** [comment]
Not sure but I think Lighting modes got removed, think i read a post saying that, can't make sure so there might be some hope

**Comment by zeux** [comment]
Should be fixed in v16, it's now Lighting.Technology though.
