### ISSUE TITLE
future is bright doesn't work in game only in studio

### ISSUE THREAD

**Issue by vonotige** [Roblox/future-is-bright#135]
everything i do i can only see in studio but when i enter through roblox player nothing has changed.

**Comment by KingHugoLi** [comment]
Because it is meant to only work in studio rn.

**Comment by vonotige** [comment]
> Because it is meant to only work in studio rn.

so whats the use?

**Comment by KingHugoLi** [comment]
Well; test it, have fun with it, make awesome pictures etc.

**Comment by vonotige** [comment]
Ok.
