### ISSUE TITLE
Run/Play/Play Here won't work // Testing games freezes

### ISSUE THREAD

**Issue by marcuss95** [Roblox/future-is-bright#138]
I've been having this issue with the Future is Bright and Vanilla ROBLOX Studio for a while. Everytime I wan't to test my games it gets stuck at 33%. The first thing that came up in my head are my scripts causing the issue. But it wasn't, I've tried Run/Play/Play Here on Baseplate. But still no luck. 

![image](https://user-images.githubusercontent.com/44327699/47260501-af2aa280-d471-11e8-9174-e5609666f008.png)

`1540067538.75860,15fc,6

Command line:
C:\Users\ayy lmao\AppData\Local\Roblox\Versions\version-318797802ea54261\RobloxStudioBeta.exe -startEvent www.roblox.com/robloxQTStudioStartedEvent

1540067538.76060,15fc,6 fetchClientSettingDataViaHttps
1540067538.76060,15fc,6 FetchClientSettingsDataAsync group "ClientAppSettings"
1540067538.76160,15fc,6 FetchClientSettingsDataAsync group "StudioAppSettings"
1540067539.65856,15fc,6 LoadClientSettingsFromFetchedString group: "ClientAppSettings"
1540067539.74556,15fc,6 LoadClientSettingsFromFetchedString group: "StudioAppSettings"
1540067539.76555,15fc,6 LoadClientSettingsFromLocal group: "ClientAppSettings"
1540067539.76655,15fc,6 LoadClientSettingsFromLocal group: "StudioAppSettings"
1540067539.76855,15fc,6 CrashReporter Start
1540067539.76955,15fc,6 Initializing CrashEvent request, url: https://data.roblox.com/Error/Dmp.ashx?filename=C%3A%5CUsers%5Cayy%20lmao%5CAppData%5CLocal%5CRoblox%5Clogs%5Clog%5FDD7FE%200%2C%20359%2C%200%2C%20249529%2ERobloxStudio%2Ecrashevent
1540067539.78958,1bc8,6 WatcherThread Started
1540067539.91964,15fc,6 Info: RobloxMainWindow::RobloxMainWindow - start
1540067540.46854,15fc,6 Info: RPC:Constructor Started server - RBX_STUDIO_3652
1540067541.14044,15fc,6 Got new browserTrackerId 32797300352
1540067541.24337,15fc,6 StudioABTests using browserTrackerId 32797300352
1540067541.59658,15fc,6 setAssetFolder C:/Users/ayy lmao/AppData/Local/Roblox/Versions/version-318797802ea54261/content
1540067541.60058,15fc,6 Reflection::load C:/Users/ayy lmao/AppData/Local/Roblox/Versions/version-318797802ea54261\ReflectionMetadata.xml
1540067546.57851,15fc,6 Info: RobloxMainWindow::showNativeLoginPageWidgets
1540067546.60350,15fc,6 Info: RobloxMainWindow::RobloxMainWindow - end
1540067601.26735,15fc,6 Info: LoginManager::onLoginClicked("felicia95", ********)
1540067603.05138,15fc,6 Info: RobloxMainWindow::showNativeStartPageWidgets
1540067617.13718,15fc,6 Info: TemplatePageController::onTemplateClicked(0)
1540067617.23212,15fc,6 Info: RobloxMainWindow::createAndShowIDEDoc with task EditPlace
1540067617.98910,15fc,6 Info: RobloxIDEDoc::open - start
1540067618.10724,15fc,6 Info: 	Locking DataModel
1540067618.12225,15fc,6 Info: 	Initializing Ogre
1540067618.12626,15fc,6 Info: 	Initializing View
1540067618.23808,15fc,6 D3D11 Adapter: ATI Mobility Radeon HD 4200 Series
1540067618.23808,15fc,6 D3D11 Adapter: Vendor 1002 Device 9712 VRAM 252 RAM 1664
1540067618.23808,15fc,6 Caps: ThreadSafe 0 Framebuffer 1 Shaders 1 Compute 0 Instancing 1 ConstBuffers 1
1540067618.23808,15fc,6 Caps: Framebuffer: MRT 8 MSAA 4 Stencil 1
1540067618.23808,15fc,6 Caps: Framebuffer: Depth16 1 Depth24 1 DepthFloat 1
1540067618.23808,15fc,6 Caps: Texture: DXT 1 PVR 0 ETC1 0 ETC2 0 Half 1
1540067618.23907,15fc,6 Caps: Texture: 3D 1 Array 1 Depth 1 MSAA 1
1540067618.23907,15fc,6 Caps: Texture: NPOT 1 PartialMips 1 CubeMipGen 1, CubeFramebuffer 1
1540067618.23907,15fc,6 Caps: Texture: Size 16384 Units 16
1540067618.23907,15fc,6 Caps: ConstantBufferSize 65536
1540067618.23907,15fc,6 Caps: 32bIdx 1
1540067618.23907,15fc,6 Caps: ColorBGR 0 HalfPixelOffset 0 RTFlip 0 MinusOneToOneDepth 0
1540067619.17028,15fc,6 Video memory size: 2009657344
1540067620.97498,15fc,6 Loaded 354 shaders from pack d3d10_1 variant FFlagFutureIsBrightPhase1_1 (974512 bytes)
1540067620.97498,15fc,6 Compiled 177 shaders in 1803 ms
1540067621.19199,15fc,6 Info: 	Initializing Explorer
1540067621.19199,15fc,6 Info: 		RobloxViewStudio::RobloxViewStudio - start
1540067621.19199,15fc,6 Info: 			Marshaller
1540067621.19199,15fc,6 Info: 			BindToWorkspace
1540067621.26198,15fc,6 Info: 		RobloxView::RobloxView - end
1540067621.26298,15fc,6 Info: 		RenderScheduler::RenderScheduler - start
1540067621.26398,15fc,6 Info: 			Marshaller
1540067621.26398,15fc,6 Info: 			BindToWorkspace
1540067621.97199,15fc,6 Info: 			ConfigureStats
1540067621.97299,15fc,6 Info: 			RenderJobCyclic
1540067622.95200,15fc,6 Info: 	Loading File : 
1540067623.27092,15fc,6 Info: 	Open Success
1540067623.47598,15fc,6 Info: RobloxIDEDoc::openPlaceSessionConfigWithStream - end
1540067623.53197,15fc,6 Info: RobloxIDEDoc::activate - start
1540067623.56997,15fc,6 Info: RobloxMainWindow::showTabWidgets
1540067626.60073,11e4,6 Info: DataModel Loading https://assetgame.roblox.com/Asset/?id=95206881
1540067631.95139,15fc,6 Info: RobloxIDEDoc::loadPlayDataModel - start
1540067632.34709,15fc,6 Info: 		RobloxViewStudio::RobloxViewStudio - start
1540067632.34709,15fc,6 Info: 			Marshaller
1540067632.34709,15fc,6 Info: 			BindToWorkspace
1540067632.34910,15fc,6 Info: 		RobloxView::RobloxView - end
1540067632.34910,15fc,6 Info: 		RenderScheduler::RenderScheduler - start
1540067632.34910,15fc,6 Info: 			Marshaller
1540067632.34910,15fc,6 Info: 			BindToWorkspace
1540067632.96201,15fc,6 Info: 			ConfigureStats
1540067632.96201,15fc,6 Info: 			RenderJobCyclic
1540067633.93395,15fc,6 Info: RobloxIDEDoc::activate - start
`

**Comment by zeux** [comment]
Should be fixed in v16.
