### ISSUE TITLE
Shadows wont work

### ISSUE THREAD

**Issue by donkeyrat** [Roblox/future-is-bright#139]
They wont show/look like they are on the max smooth settings.

**Comment by UncleGPU** [comment]
Is the Future is Bright option checked under Rendering? Click on FILE, then Settings, and then click Rendering. Scroll down to the "Future is Bright" checkbox. If it's checked, then something's wrong. If it's not checked, then click on it and restart Studio.

**Comment by zeux** [comment]
Closing this assuming this is fixed in v16, note that in v16 lighting is controlled via Lighting.Technology enum.
