### ISSUE TITLE
FiB Studio Constantly Hanging

### ISSUE THREAD

**Issue by UnsatisfiedPrius** [Roblox/future-is-bright#140]
Ever since last week, FiB has been constantly hanging because of the toolbox. It happens when I open a place, when studio autosaves, and when I try to interact with the toolbox. When I close the toolbox, everything works completely fine. It seems that studio is running into issues when connecting to the toolbox or something. Is this a widespread issue, or am I the only person having this problem?

If it matters or makes any difference, I'm currently running on a Windows 10 machine with 16 gigs of RAM and FiB is stored in My Documents.

**Comment by adasgadfg** [comment]
same here

**Comment by zeux** [comment]
Should be fixed in v16. v16 is slightly rough in terms of actual lighting code but it seems better than not having v15 work at all :)
