### ISSUE TITLE
Weird lines when zoomed out

### ISSUE THREAD

**Issue by Sparkypen7** [Roblox/future-is-bright#15]
Not sure if it's my graphics card, or the actual prototype, but weird lines appeared when I moved my camera angle furthest away from me possible.

![image](https://user-images.githubusercontent.com/11379504/28496218-dc378b34-6f33-11e7-9eb4-8796c062f956.png)

**Comment by Reshiram110** [comment]
I've been experiencing similar issues with shadows, shadows will get cut-off halfway as if they've stopped rendering when I zoom out far enough.

**Comment by LouieK22** [comment]
Yep, same thing happened to me.

**Comment by zeux** [comment]
Yeah, this is a tuning issue for the current prototype. What's the TimeOfDay for this level?

**Comment by Sparkypen7** [comment]
@zeux It's just 14:00:00

**Comment by Kolinchkov** [comment]
This would seem not to be limited to only distant views, but rather this occurs : https://gyazo.com/c1a87fc49639c1ff91923f306e738df5

**Comment by craftsmashbuild** [comment]
Same issues as @Kolinchkov said

**Comment by tsbuilderboy** [comment]
From what I've seen of it, I think it may have something to do with the LoD, but I don't know.

**Comment by zeux** [comment]
This should be fixed in v12.
