### ISSUE TITLE
[V16] Broke Volumetric Lighting.

### ISSUE THREAD

**Issue by SethizFTW** [Roblox/future-is-bright#151]
It was a little trick that was able to be done in V15 but I guess with the shadow changes in V16 I guess it was "fixed"? Disappointing but I am curious if there is interest in Volumetric Lighting becoming apart of roblox.
![image](https://user-images.githubusercontent.com/30537722/53129629-0fbc1000-3536-11e9-9f7c-6680636a6b03.png)
![image](https://user-images.githubusercontent.com/30537722/53129653-206c8600-3536-11e9-8906-26397c11926b.png)

**Comment by plasma-node** [comment]
Yeah I am getting the same issue.

It's because shadows render differently on billboard guis and beams now

**Comment by SethizFTW** [comment]
> Yeah I am getting the same issue.
> 
> It's because shadows render differently on billboard guis and beams now

Yea I had figured that and it is disappointing. It
