### ISSUE TITLE
ShadowMap - Ambient and OutdoorAmbient do not behave as expected

### ISSUE THREAD

**Issue by hunte922** [Roblox/future-is-bright#18]
![screenshot_105](https://user-images.githubusercontent.com/5272529/28496867-66841048-6f3c-11e7-9f51-7ce9fd711b6b.png)
The two properties seem to mix together to form one lighting color. As a result, the shadow color cannot be changed.

**Comment by LouieK22** [comment]
Same thing happened to me. It got darker by setting OutdootAmbience to lighter color.

**Comment by ImperatorDuncan** [comment]
I'm suffering the same issue, sometimes it shows opposite colors from what I've selected it to display.

**Comment by Kolinchkov** [comment]
I shall be experiencing just the same. Quite an odd situation.

**Comment by tsbuilderboy** [comment]
Huh, it's different for me. For me, Ambient does nothing, and OutdoorAmbient set the shadow color.

**Comment by zeux** [comment]
This should be fixed in v12 as the hybrid mode uses correct formula to combine ambient & outdoorambient.
