### ISSUE TITLE
Lighting artifacts, spazzing, and overall shading glitches

### ISSUE THREAD

**Issue by TheSink** [Roblox/future-is-bright#19]
I'm guessing this is already known, but I'm gonna put it here anyways.
This video should explain it much better.
[YouTube Video](https://www.youtube.com/watch?v=1824IvNXO08)
Shading bugs, lighting has a seizure, and there are lighting artifacts/lines/less-rendered areas all around.
Do note - this only seems to occur for me with SurfaceLights and SpotLights. PointLights don't spaz out like this.

**Comment by hunte922** [comment]
Video doesn't work. Is this the same issue as #13?

**Comment by TheSink** [comment]
I'll upload it to YouTube real quick. It's sorta the same, although it's more of the rendering system having a seizure than anything.

**Comment by hunte922** [comment]
Looks like a performance bottleneck to me. You're using the VoxelGPUCascaded mode, correct? What CPU and graphics card are you sporting?

**Comment by tsbuilderboy** [comment]
The spazzing isn't a glitch. It's the LoD. It just looks weird because the camera in ROBLOX Studio moves pretty fast.

**Comment by zeux** [comment]
Since we discontinued the voxel gpu mode and worked a lot on other things this seems to not be relevant anymore, closing.
