### ISSUE TITLE
Crash upon selecting ShadowMap lighting mode

### ISSUE THREAD

**Issue by TheSink** [Roblox/future-is-bright#2]
Specs: 
Processor - AMD FX-6300 Six-core
Graphics card - Nvidia GTX 1050 Ti
8gb DDR4 RAM
Windows 7 Ultimate

Studio crashes upon selecting the "ShadowMap" lighting mode. Selecting GPUCascaded works fine. Crashes on any map, no matter where you are, how many programs you have open, etc. I have a DX12-compatible card, 4GB VRAM, and Windows 7 which meets the criteria on the github page.

**Comment by iiTouge** [comment]
Is there anything you put in the game while have this map turned on?

**Comment by TheSink** [comment]
Hmm? I can edit the map fine. If you mean adding stuff to the place while having ShadowMap on, I simply cannot turn it on at all. It refuses to turn on, and crashes immediately, even on a simple baseplate.
http://i.imgur.com/YsVDfBN.png

**Comment by Kolinchkov** [comment]
I am having the same issue as well. As aforementioned, the selection of "Shadowcast" causes ROBLOX to crash and with any creation I have selected thus far.

Specifications:
Processor - AMD FX-8350 Eight-Core Processor
Graphics Processing Unit - AMD R9 270x 4 Gigs Onboard RAM
RAM - 16 Gigs DDR4
OS - Windows 7 Ultimate

**Comment by TheSink** [comment]
Could be AMD processors? I'd have to see more people with the same issue.

**Comment by LouieK22** [comment]
@iiTouge What's your specs?

**Comment by iiTouge** [comment]
Windows 10, Intel Core i5 3210M 2.50GHz, 4 GB RAM, 64 bit processor.

**Comment by LouieK22** [comment]
@iiTouge Does it crash or just lag a lot?

**Comment by iiTouge** [comment]
Its not me, but I do experience a little lag. Ive been trying to help people.

**Comment by index4444** [comment]
I've got Windows 7 and the same issue happens to me.

Specifically:
Windows 7 64-bit with Directx 11
AMD phenom II X4 B50 processor @ 3.2GHz
12GB RAM
Nvidia Geforce GTX 750 TI 2GB VRAM

**Comment by iiTouge** [comment]
Wel they are going to ship their new performance upgrade soon with 2x the speed. As said at RDC.

**Comment by LouieK22** [comment]
It seems to be a very strong correlation between AMD processors and this crash on shadow map.

**Comment by TheSink** [comment]
Possibly an issue with anyone using Windows 7 alongside an AMD processor? Those are the two most apparent similarities between all of us.

**Comment by LouieK22** [comment]
Issue #13 confirms that AMD processors are not causing this.

**Comment by LouieK22** [comment]
Friend replicated issue, Windows 7, screenshot of specs https://cdn.discordapp.com/attachments/262031007962759170/338532276206043137/image.png This pretty much rules out any blame on AMD CPUs.

**Comment by TheSink** [comment]
Seems like it's a windows 7 issue then. Interesting.

**Comment by zeux** [comment]
Would you mind:

1) Running prototype Studio build to trigger the issue
2) Going to C:\Users\username\AppData\Local\Roblox\logs
3) Uploading the latest file with _1.txt suffix here?

**Comment by Kolinchkov** [comment]
`0.51461 1828: setAssetFolder content
0.96860 1828: CrashReporter Start
0.96860 18a0: WatcherThread Started
0.97060 1828: Initializing CrashEvent request, url: https://data.roblox.com/Error/Dmp.ashx?filename=C%3A%5CUsers%5CTRISTAN%5CAppData%5CLocal%5CRoblox%5Clogs%5Clog%5FAF472%200%2C%20299%2C%201%2C%20137593%2EClient%2Ecrashevent
1.08663 1828: Error: Important !Loading shader files
1.12156 1828: Info: Initializing new game
1.12356 1828: account = UA-43420590-14, schedule = 500
1.19452 1828: D3D11 Adapter: AMD Radeon R9 200 Series
1.19452 1828: D3D11 Adapter: Vendor 1002 Device 6810 VRAM 3072 RAM 1023
1.22357 1828: Video memory size: 4272136192
1.24057 1828: Loaded shaders from pack d3d11
1.24057 1828: Compiled 137 shaders in 17 ms
1.26157 1828: Loaded 16 fonts in 5 ms
1.33757 09dc: PlaceLauncher URL : https://assetgame.roblox.com/game/PlaceLauncher.ashx?request=RequestGame&browserTrackerId=9783257674&placeId=858546149&isPartyLeader=false
1.58069 09dc: PlaceLauncher Response : {"jobId":"b5e0d98c-0732-40d0-ac20-50811eae32ec","status":2,"joinScriptUrl":"https://assetgame.roblox.com/Game/Join.ashx?ticketVersion=2&ticket=%7b%22UserId%22%3a7386586%2c%22UserName%22%3a%22Xurxes%22%2c%22CharacterFetchUrl%22%3a%22https%3a%2f%2fapi.roblox.com%2fv1.1%2favatar-fetch%2f%3fplaceId%3d858546149%26userId%3d7386586%22%2c%22GameId%22%3a%22b5e0d98c-0732-40d0-ac20-50811eae32ec%22%2c%22PlaceId%22%3a858546149%2c%22UniverseId%22%3a356040525%2c%22IsTeleport%22%3afalse%2c%22FollowUserId%22%3anull%2c%22TimeStamp%22%3a%227%2f23%2f2017+12%3a58%3a56+AM%22%2c%22CharacterAppearanceId%22%3a7386586%2c%22AlternateName%22%3anull%7d&signature=GMuVWseTzEJptpN499u4Mqa7wQEwZO7sJfXDG5Ae9l9z9hoCIZMW1My56FoS1R14%2bW4xpTkBHZVrGZ%2fyAWbUAdmtDkNt%2bLE3L3YsRr8Sf8G9UnhqapNVwnez%2bIdGqwUJh5c0aOrLKPc44Iqn4KDIWi7YFBQijzfI%2fARoJRlNgCs%3d&connectionInfo=bJ5ZzBIdZ%2b%2b3%2fXdp5nsddc6Y8mQN4LaU5pEq1jU3QhkNB42tCUf9yXW62hf3PllAwhYt9OgIcPftqjEUfJmXZmWlVFw%3d&browserTrackerId=9783257674","authenticat
1.90358 1a40: ! Joining game 'b5e0d98c-0732-40d0-ac20-50811eae32ec' place 858546149 at 23.105.47.154
1.94054 1a40: Connecting to 23.105.47.154:63511
2.12165 193c: Connection accepted from 23.105.47.154|63511
2.32273 0a70: Warning: ClassDescriptor failed to learn ThumbnailGenerator
44.20511 0c04: bounds isActive true
45.18808 0c04: bounds isActive false`

If not this then:
`0.56560 182c: setAssetFolder content
0.99567 182c: CrashReporter Start
0.99567 14d4: WatcherThread Started
0.99667 182c: Initializing CrashEvent request, url: https://data.roblox.com/Error/Dmp.ashx?filename=C%3A%5CUsers%5CTRISTAN%5CAppData%5CLocal%5CRoblox%5Clogs%5Clog%5FCCA06%200%2C%20299%2C%201%2C%20137593%2EClient%2Ecrashevent
1.11556 182c: Error: Important !Loading shader files
1.14955 182c: Info: Initializing new game
1.15055 182c: account = UA-43420590-14, schedule = 500
1.21956 182c: D3D11 Adapter: AMD Radeon R9 200 Series
1.22056 182c: D3D11 Adapter: Vendor 1002 Device 6810 VRAM 3072 RAM 1023
1.24857 182c: Video memory size: 4272136192
1.26557 182c: Loaded shaders from pack d3d11
1.26557 182c: Compiled 137 shaders in 16 ms
1.28557 182c: Loaded 16 fonts in 6 ms
1.36157 0318: PlaceLauncher URL : https://assetgame.roblox.com/game/PlaceLauncher.ashx?request=RequestGame&browserTrackerId=9783257674&placeId=34972152&isPartyLeader=false
1.60557 0318: PlaceLauncher Response : {"jobId":"JoinPlace=34972152;","status":0,"joinScriptUrl":null,"authenticationUrl":null,"authenticationTicket":null,"message":null}
2.66663 0318: PlaceLauncher Response : {"jobId":"JoinPlace=34972152;","status":0,"joinScriptUrl":null,"authenticationUrl":null,"authenticationTicket":null,"message":null}
4.02473 0318: PlaceLauncher Response : {"jobId":"JoinPlace=34972152;","status":0,"joinScriptUrl":null,"authenticationUrl":null,"authenticationTicket":null,"message":null}
5.77381 0318: PlaceLauncher Response : {"jobId":"12be2919-2752-4ca9-b3b6-7062afe1c220","status":2,"joinScriptUrl":"https://assetgame.roblox.com/Game/Join.ashx?ticketVersion=2&ticket=%7b%22UserId%22%3a7386586%2c%22UserName%22%3a%22Xurxes%22%2c%22CharacterFetchUrl%22%3a%22https%3a%2f%2fapi.roblox.com%2fv1.1%2favatar-fetch%2f%3fplaceId%3d34972152%26userId%3d7386586%22%2c%22GameId%22%3a%2212be2919-2752-4ca9-b3b6-7062afe1c220%22%2c%22PlaceId%22%3a34972152%2c%22UniverseId%22%3a10303841%2c%22IsTeleport%22%3afalse%2c%22FollowUserId%22%3anull%2c%22TimeStamp%22%3a%227%2f23%2f2017+12%3a52%3a05+AM%22%2c%22CharacterAppearanceId%22%3a7386586%2c%22AlternateName%22%3anull%7d&signature=G35lAFJl%2bLCy6gYBehRTWjhhlC0JtScXdt%2fgwEzMNEuibNB3U1mM0XnWTXFFkjEpykV%2f1BxOTD8GdWT8OOm2XP57%2bUSXCQ5Xovx%2f3cBllh%2fyRlKxNd7HIgyTW61PQFsCnO8W1gsYcM%2bW7ziKC8SH9aNkTZagBiSCn21%2bqVo4dQA%3d&connectionInfo=ZNNKxl2xraFhXZtjuLz9i%2bwCw%2fqdkosSTPwq9Ci5ufEt1lgO0hSl23eLNdnZQhudZiE2OQ6SMIEWFrFvLyT6oVg4Tw0%3d&browserTrackerId=9783257674","authentica
6.13386 0a70: ! Joining game '12be2919-2752-4ca9-b3b6-7062afe1c220' place 34972152 at 172.98.69.72
6.16687 0a70: Connecting to 172.98.69.72:57282
6.29979 0a70: Connection accepted from 172.98.69.72|57282
6.53483 11d0: Warning: ClassDescriptor failed to learn ThumbnailGenerator
6.61774 0a70: Assets loaded
110.10541 182c: Error: CmdBar is not a valid member of Frame
110.10541 182c: Info: Stack Begin
110.10541 182c: Info: Script 'ReplicatedFirst.

', Line 120
110.10541 182c: Info: Stack End
110.10641 182c: Error: CmdBar is not a valid member of Frame
110.10641 182c: Info: Stack Begin
110.10641 182c: Info: Script 'ReplicatedFirst.

', Line 120
110.10641 182c: Info: Stack End
110.10641 182c: Error: CmdBar is not a valid member of Frame
110.10641 182c: Info: Stack Begin
110.10641 182c: Info: Script 'ReplicatedFirst.

', Line 120
110.10641 182c: Info: Stack End`

**Comment by zeux** [comment]
Turns out we actually have crash reporting working on this build and we have a solid number of crashes. I'll look into this on Monday, thanks!

**Comment by od149** [comment]
This only seems to be happening on windows 7, i have windows 10 on another hard drive on my pc and it works fine when turning shadow map on, but on windows 7 it instantly crashes.

**Comment by cvchisholm** [comment]
So as of today i actually got it to work under windows 7. Using Vulkan instead of DirectX it can do ShadowMap rendering. And this aint a powerful card either, its a 1gb EVGA GT 710

Unrelated to the issue but to the comments, how on earth are some of you using DDR4 on Am3+ motherboards with FX series processors?

**Comment by zeux** [comment]
Windows 7 issue is fixed in v2: download it from https://github.com/Roblox/future-is-bright/releases

**Comment by Rocky28447** [comment]
Sweet! Arseny, you're a god, my man!
