### ISSUE TITLE
Can't open up a place or start a new pne

### ISSUE THREAD

**Issue by MarcusDeving** [Roblox/future-is-bright#24]
It says it is loading and when it is done loaded, I am still on the start page :|

**Comment by neopy2** [comment]
same issue

**Comment by oreocookiezii** [comment]
same issue

**Comment by MarcusDeving** [comment]
helpfull :|

**Comment by jhonatanxxxbeiral** [comment]
same issue

**Comment by zeux** [comment]
There is a new build (v2) on this page https://github.com/Roblox/future-is-bright/releases - it should either work or clearly indicate that your system is currently not supported.
