### ISSUE TITLE
When trying to use "shadow map" Roblox studio crashes

### ISSUE THREAD

**Issue by od149** [Roblox/future-is-bright#26]

**Comment by hunte922** [comment]
Duplicate of #2. You need to turn on GlobalShadows before enabling ShadowMap.

**Comment by hunte922** [comment]
You've posted this twice (#27). Can you close this one since it's less detailed?

**Comment by zeux** [comment]
Fixed in v2, download it from https://github.com/Roblox/future-is-bright/releases
