### ISSUE TITLE
Compatibility on Mac/OX?

### ISSUE THREAD

**Issue by DankLifeForever** [Roblox/future-is-bright#3]
Is there going to be a release on Mac/OX?

**Comment by AchievedData** [comment]
I was having the same problem.

**Comment by AchievedData** [comment]
I was thinking the same thing.

**Comment by iiTouge** [comment]
Im pretty sure there might be soon, you are missing out. Its amazing how if you take a light away that was super bright your camera (view) has to adjust back to normal lighting.

**Comment by DankLifeForever** [comment]
I know, this lighting could make my game even better. Sadly, I'm a developer using a Apple product to develop on ROBLOX.

**Comment by iiTouge** [comment]
I personally love it, the realism that they aimed for is really good.

**Comment by iiTouge** [comment]
I wish we could release the prototype but it is prototype

**Comment by zeux** [comment]
We absolutely plan to support OSX but it will take a bit of time so it wasn't possible to do before RDC.

**Comment by zeux** [comment]
This is fixed in v10; note that it requires Metal-compatible Macbook and we didn't really test/optimize this too thoroughly so there might be issues.
