### ISSUE TITLE
ShadowMap - Shadow-casting lights spontaneously stop casting shadows

### ISSUE THREAD

**Issue by hunte922** [Roblox/future-is-bright#30]
Enabling/disabling shadows or the entire light source doesn't seem to fix it. The lights usually stop working after waiting a long time.

**Comment by zeux** [comment]
Something must be up with the shadow caching system... Do you have a repro for this that I can follow?

**Comment by hunte922** [comment]
Not at this moment, but I'll keep you posted.

**Comment by zeux** [comment]
Closing for now, feel free to reopen or file a new bug if you reproduce this.
