### ISSUE TITLE
places not loading up even though i have the right graphics card

### ISSUE THREAD

**Issue by MinecraftDude98** [Roblox/future-is-bright#31]
Roblox studio will not work even though i have DirectX 11.1

**Comment by qu47** [comment]
#12

**Comment by zeux** [comment]
There were a few reasons that could cause this (such as changing the GraphicsMode...) - the new build which you can download from https://github.com/Roblox/future-is-bright/releases  should either work or clearly indicate that your system is currently incompatible.

**Comment by MinecraftDude98** [comment]
@zeux 

That still dosen't work. I get this now:

![untitled](https://user-images.githubusercontent.com/15851867/28587177-3e77abfa-7144-11e7-91e0-ecaf9e383326.png)

And im running directx11.1 on windows 10.

**Comment by zeux** [comment]
Can you post a screenshot of dxdiag with the Display tab? Most likely your GPU doesn't actually support DirectX 11.

**Comment by MinecraftDude98** [comment]
![untitled](https://user-images.githubusercontent.com/15851867/28841465-57c6fde8-76c8-11e7-86b7-040a898782e9.png)

**Comment by zeux** [comment]
Yeah, Feature Levels in this screenshot suggests that your GPU does not support DirectX 11 - it only supports DirectX 10.1. You can watch issue #38 to get notified when we add support for DX10/10.1.
