### ISSUE TITLE
some issues I've found that involve LoD and crashing

### ISSUE THREAD

**Issue by DucktorSpiffy** [Roblox/future-is-bright#32]
First bug:
When testing performance by generating a 20x20 square of point light parts, I found that the closer I got to the center, some lights would stop rendering despite the fact I was close to them and when I got further away, they appeared again. [Here's an image of what happened](https://twitter.com/DucktorSpiffy/status/889162781987135492)

Second bug:
I saw that the shadowmap was no longer rendering any shadows and that there was some random ominous incredibly large shadow that disappeared depending on camera angle. I tried to fix this by going from Shadowmap to VoxelCPU and back, but all that did was crash when I tried to go back to Shadowmap.

**Comment by zeux** [comment]
On the first bug, it's more or less intentional; we'll take a closer look at this later this year.
Second issue should be gone probably, closing this for now. Feel free to file a new bug if you find something in recent builds.
