### ISSUE TITLE
Setting angle of Spotlights to zero with shadows on in ShadowMap messes up rendering

### ISSUE THREAD

**Issue by David-Cosby** [Roblox/future-is-bright#33]
It's kinda hard to explain what this does, so I'm just going to drop a gif by here.
This issue happens with lights of all colors and also with SurfaceLights

![wierdness with spotlights](https://user-images.githubusercontent.com/29415120/28533248-a89392ce-7059-11e7-8452-79d13108a7a2.gif)

**Comment by zeux** [comment]
Will be fixed in v3.

**Comment by RodjGaming** [comment]
@zeux Is this the same thing as what was happening in #7?
