### ISSUE TITLE
Custom Studio isnt working

### ISSUE THREAD

**Issue by Forrsch** [Roblox/future-is-bright#34]
Hello! I seem to be the only one having this issue. Or maybe not, but so far no one has been able to help me.
(Fastfoward after downloading the zip file)
I extract the folder into Documents.
I then open up RobloxStudioBeta.exe
I select new baseplate.
White screen occupies the place where the whole studio should be.
Ive tried to uninstall and reinstall it numerous times, but it still has the white screen. I cant ever get it to work. It might be my windows, but I have windows 10 and im pretty sure its supposed to work with that.
I also then tried to extract it to different files, but it still never works.

Any help please? It will be very much appreciated, and thanks in advance.

**Comment by zeux** [comment]
There were a few reasons that could cause this (such as changing the GraphicsMode...) - the new build which you can download from https://github.com/Roblox/future-is-bright/releases  should either work or clearly indicate that your system is currently incompatible.

**Comment by Forrsch** [comment]
My system runs of DirectX 12, and runs windows 10 as you already know. It doesnt say that its not compatible, so it might be because of the GraphicsMode. Anyway. thank you this information
