### ISSUE TITLE
Can't open RobloxStudioBeta.exe

### ISSUE THREAD

**Issue by Rytimiscurisin** [Roblox/future-is-bright#35]
I download the zip, open the folder, and doubleclick RobloxStudioBeta.exe, for a second something is loading but then it disappears and a popup says that it can't proceed because "Qt5Gui.dll was not found". It proceeds to tell me to try reinstalling the program. Once I click okay, the same popups come up for Qt5Widgets.dll, Qt5Core.dll, and Qt5Network.dll. I have tried downloading the zip again but this keeps happening. I can easily find these dll files on my own, I'm not sure why it's saying they aren't there.

**Comment by Rytimiscurisin** [comment]
If it means anything, I also have normal studio installed and it never does this.

**Comment by Rytimiscurisin** [comment]
Also just tried V2, same problem.

**Comment by zeux** [comment]
The issue must be that you can't launch the .exe from the .zip directly - you have to copy the entire folder somewhere, and then open it there and run Studio.

**Comment by Rytimiscurisin** [comment]
I'm an idiot, whoops. Working now; thanks and good luck.
