### ISSUE TITLE
Turning off GlobalShadows after switching to ShadowMap breaks the shadows

### ISSUE THREAD

**Issue by Ghomaghity** [Roblox/future-is-bright#36]
After messing around for a while, I found that GlobalShadows affects how shadows are made.

**Comment by Ghomaghity** [comment]
![image](https://user-images.githubusercontent.com/30422029/28549934-2bbafbbc-70a3-11e7-8b47-655ddf759ef9.png)

Another example...

**Comment by Ghomaghity** [comment]
I found the real cause of the glitch. I thought through thorough testing brightness was the cause but i found something different.

**Comment by zeux** [comment]
Can you provide a video/gif with the glitches?

**Comment by Ghomaghity** [comment]
Sorry, I'm new with this
Before:
![image](https://user-images.githubusercontent.com/30422029/28552522-7dc954ec-70b4-11e7-8f4f-a64ac8540b42.png)
After:
![image](https://user-images.githubusercontent.com/30422029/28552503-61c47e7a-70b4-11e7-92c0-9f74fe217d61.png)

I changed the title because I found the actual source of the glitch

**Comment by zeux** [comment]
Fixed in v3
