### ISSUE TITLE
Quote, "Future is bright" Not working ::)

### ISSUE THREAD

**Issue by WolfKOTTO** [Roblox/future-is-bright#37]
This was a **COMPLETE WASTE OF TIME** it doesn't work at all. First, starting roblox studio, loading, loaded everything functions every little thing works but, the screen is still stuck on the menu. I want this to be fixed right now otherwise I'll be stuck in a white screen forever

**Comment by zeux** [comment]
There were a few reasons that could cause this (such as changing the GraphicsMode...) - the new build which you can download from https://github.com/Roblox/future-is-bright/releases  should either work or clearly indicate that your system is currently incompatible.

**Comment by WolfKOTTO** [comment]
Understandable.

**Comment by WolfKOTTO** [comment]
Sorry for the inconvenience
