### ISSUE TITLE
Support Direct3D 10/10.1

### ISSUE THREAD

**Issue by WolfKOTTO** [Roblox/future-is-bright#38]
I've been proven wrong before and now the Roblox Studio says my system isn't compatable to DirectX11. This can be a problem I don't know what I can do about it

**Comment by zeux** [comment]
My guess is that you currently can't do anything about it since the prototype requires DirectX 11. Pretty sure our detection code for this is rock-solid; you can run dxdiag and post a screenshot of first "Display" tab that will show your GPU/etc. spec.

**Comment by zeux** [comment]
(I will keep this issue open for any similar reports but do keep in mind that we currently just don't support systems that aren't DirectX 11 compatible; this will change in the future)

**Comment by WolfKOTTO** [comment]
Got it, here's an image of the dxdiag if you need it

![image](https://user-images.githubusercontent.com/30423981/28552447-509cb70e-70a3-11e7-8e19-14c9b75c2447.png)

**Comment by zeux** [comment]
Can you post a screenshot of the Display tab?

**Comment by WolfKOTTO** [comment]
Certainly. 

![image](https://user-images.githubusercontent.com/30423981/28552541-d10e3ec6-70a3-11e7-8633-b2baa376ad00.png)

**Comment by zeux** [comment]
Yeah, so you don't actually have DirectX 11 support (dxdiag is misleading on the first page) - your GPU only supports DirectX 10.1 (see DDI Version on this page). We are absolutely planning to support Direct3D 10.1 but this won't happen super quickly I'm afraid.

**Comment by WolfKOTTO** [comment]
I understand, it is worth the wait I suppose

**Comment by zeux** [comment]
This should be fixed in v6 for ShadowMaps mode; VoxelCascadedGPU still doesn't support Direct3D 10 at this time.

**Comment by zeux** [comment]
Since we don't have plans to support VoxelCascadedGPU on Direct3D 10 I am closing this.
