### ISSUE TITLE
Windows 7 shadowmap support.(Fixed, dont mind this)

### ISSUE THREAD

**Issue by starcon2** [Roblox/future-is-bright#39]
Shadowmap does not work on windows 7, we have done tests with windows 10 and it works fine with same specs.

I cant use shadowmap on windows 7 myself, as it crashs instantly.

my specs are:
gtx 1060 6gb
amd fx 8350 4.0ghz
windows 7

Please fix this.

**Comment by TheSink** [comment]
You can close the issue instead of updating the title using the "Close Issue" button by the Comment button.
