### ISSUE TITLE
Place Opening Visibility

### ISSUE THREAD

**Issue by DudeWithTheMetalHat** [Roblox/future-is-bright#4]
Everything works fine, except for actually being able to see the place... can still change settings and properties.

**Comment by iiTouge** [comment]
You cant see anything?

**Comment by Diffle** [comment]
Same.

**Comment by DudeWithTheMetalHat** [comment]
@iiTouge Not a thing.

**Comment by iiTouge** [comment]
Again very buggy, I recommend restarting tell me what happens then.

**Comment by DudeWithTheMetalHat** [comment]
I'll give it a try.

**Comment by iiTouge** [comment]
anything?

**Comment by DudeWithTheMetalHat** [comment]
nope, same problem.

**Comment by iiTouge** [comment]
As told bugs we cant really deal with sorry, im not sure why this happens. Try opening normal studio to make sure everything is ok

**Comment by DudeWithTheMetalHat** [comment]
this is very saddening, was really hyping myself up for 6+ hours. oh well.

**Comment by DudeWithTheMetalHat** [comment]
@iiTouge Alright so I got a screenshot, which is what i should've had in the first place. This is all that I can see.
![blank](https://user-images.githubusercontent.com/30379905/28495981-ff68ea28-6f2c-11e7-85f9-25463f316451.png)

**Comment by LouieK22** [comment]
What are your computer's specs?

**Comment by Biddn** [comment]
I go to File >Settings >Rendering >Graphics Mode Changing it to Direct3D11 or Automatic should fix it.

**Comment by zeux** [comment]
Yeah make sure your GraphicsMode is set to Direct3D11 or Automatic - OpenGL won't work with the new lighting build.

If GraphicsMode is already set correctly, please:

1) Run prototype Studio build to trigger the issue
2) Go to C:\Users\username\AppData\Local\Roblox\logs
3) Upload the latest file with _1.txt suffix here

**Comment by Diffle** [comment]
I have installed DirectX 12, but in log I get "Your graphics drivers seem to be too old for Roblox to use."
I think mine PC is too weak.

**Comment by zeux** [comment]
There were a few reasons that could cause this (such as changing the GraphicsMode...) - the new build which you can download from https://github.com/Roblox/future-is-bright/releases should either work or clearly indicate that your system is currently incompatible.
