### ISSUE TITLE
Shadowmap - SurfaceLights with Shadows Enabled Bug

### ISSUE THREAD

**Issue by AshCraft1337** [Roblox/future-is-bright#42]
![image](https://user-images.githubusercontent.com/30395035/28577890-00c842e2-7126-11e7-8187-1e31665f3ae8.png)

^ with shadows enabled

![image](https://user-images.githubusercontent.com/30395035/28577902-0c04eb6a-7126-11e7-9757-55e1bfafc2ab.png)

^ with shadows disabled

not sure if this is a bug or its from my end but ill post it anyway

**Comment by AshCraft1337** [comment]
nevermind this is a duplicate of a post of #13 

my bad

**Comment by zeux** [comment]
I'm not sure it's a duplicate - it might be the same issue as #29 but I am not sure. Can you post the level above?

**Comment by AshCraft1337** [comment]
here ya go 

[surfacelightglitch.zip](https://github.com/Roblox/future-is-bright/files/1174939/surfacelightglitch.zip)

**Comment by zeux** [comment]
Yeah that was a separate bug. Will be fixed in v3.
