### ISSUE TITLE
ShadowMap buffer doesn't get cleared when GlobalShadows is set to false.

### ISSUE THREAD

**Issue by CloneTrooper1019** [Roblox/future-is-bright#44]
If you turn off GlobalShadows while in ShadowMap mode, the most recently rendered shadow map stays in the buffer. It looks really weird when moving the camera around.

**Comment by Rytimiscurisin** [comment]
That may be the same case as #36 . Can you send a gif of this?

**Comment by zeux** [comment]
Duplicate of #36
