### ISSUE TITLE
Future Is Bright link are totally not respectfull.

### ISSUE THREAD

**Issue by RahadianNorman** [Roblox/future-is-bright#47]
*RACIST LINK* they only have limited time for download, please respect people with slow connection to donwload the link without limited time address.

**Comment by DucktorSpiffy** [comment]
Don't clog up issues with stuff like this.

**Comment by zeux** [comment]
This project is hosted on GitHub; if there are any rate limits or download timeouts, it's entirely on GitHub; feel free to contact them for support.
