### ISSUE TITLE
lighting through transparent objects

### ISSUE THREAD

**Issue by gulp78** [Roblox/future-is-bright#49]
![robloxscreenshot20170729_214932529](https://user-images.githubusercontent.com/30380910/28744647-96d03c10-74a8-11e7-8940-a77f77fc49a5.png)

i had a spotlight from some train lights and made the spotlight do shadows from objects, but i thought that maybe it will go through transparent objects a little so i put a block in front of it with 0.5 transparency to test if transparent objects would let a little light through it... but it acted like it was a solid object and not transparent (this is with shadowmap btw)

**Comment by Knightshade** [comment]
I made a quick test with the first part being fully solid and increasing transparency by 0.1 for each block. It stops blocking at 0.502 or higher.

![transparency](https://user-images.githubusercontent.com/6109240/28749349-12568552-748a-11e7-8468-c9999353d784.png)

**Comment by gulp78** [comment]
is that with shadows enabled on the spotlight?

**Comment by Knightshade** [comment]
Yes shadows are enabled.

**Comment by Extuls** [comment]
It's easy to reproduce. The difference seems to occur between 0.501 and 0.502.

![image](https://user-images.githubusercontent.com/30379868/28808269-a579693e-7648-11e7-99e7-95ddab915e1b.png)

**Comment by DragonSkye** [comment]
Just wondering but does the light mapping have occlusion with it?

**Comment by tsbuilderboy** [comment]
With Glass it starts at 0.001.

**Comment by zeux** [comment]
0.5 cutoff for shadows is intentional - I don't think we'll change this (although maybe we will change the cutoff) - our current implement of shadowmaps just doesn't support translucency.
