### ISSUE TITLE
Specular Highlights (?) Showing from Light Source Behind a wall

### ISSUE THREAD

**Issue by Extuls** [Roblox/future-is-bright#5]
The light this is coming from is inside the building. This doesn't seem like intended behavior and I don't know if it's known, so I'm posting it here. (This is ShadowMap by the way)

![image](https://user-images.githubusercontent.com/30379868/28495757-4263dd34-6f27-11e7-84c6-6899766d4d91.png)

**Comment by Extuls** [comment]
Oh, and this is ShadowMap, but I'm sure that's clear already.

**Comment by iiTouge** [comment]
Weird, its a bug then unless you have any other lighting stuff around that building. I thinks its a bug.

**Comment by iiTouge** [comment]
Make the light brighter and see if it changes.

**Comment by Extuls** [comment]
I turned down the range and turned up the brightness.

![image](https://user-images.githubusercontent.com/30379868/28495796-31fd6e32-6f28-11e7-8449-e615b159c3c4.png)

**Comment by iiTouge** [comment]
So its a bug with the range, nothing we can do 👎

**Comment by zeux** [comment]
Can you post this level or another level that reproduces this issue?

**Comment by Extuls** [comment]
No longer seems to happen in v2.
