### ISSUE TITLE
Shadows don't display with constraints

### ISSUE THREAD

**Issue by DragonSkye** [Roblox/future-is-bright#52]
[![https://gyazo.com/a1359d95191fb7c2fe8869fdb62d0cf1](https://i.gyazo.com/a1359d95191fb7c2fe8869fdb62d0cf1.gif)](https://gyazo.com/a1359d95191fb7c2fe8869fdb62d0cf1)

As you can see the rope constraint I am using is not being shown with the shadow.

**Comment by hunte922** [comment]
Constraints were never affected by the old shadows, so this is more of a feature request.

**Comment by DragonSkye** [comment]
well I'm not yet able to add label or don't know how to on this issue request

**Comment by hunte922** [comment]
All you can do is wait for zeuxcg to label it. I was just clarifying what this was for any potential readers.
