### ISSUE TITLE
SpotLight.Angle=0 produces artifacts with ShadowMap

### ISSUE THREAD

**Issue by Fraktality** [Roblox/future-is-bright#55]
Enable ShadowMap and create a SpotLight in a part.  Setting the SpotLight's Angle to 0 produces a black artifact in front of the SpotLight.

![98f76a6e62ef0608988a28b6c61bd44c](https://user-images.githubusercontent.com/3611985/28840861-5af9a274-76c6-11e7-8bb1-0762a53512bd.gif)

![1b61246fd9f966a8771002153308aaee](https://user-images.githubusercontent.com/3611985/28841148-40679c3a-76c7-11e7-8fb0-29ea1520ff79.png)

**Comment by zeux** [comment]
Which build is this? This should be fixed in v3.

**Comment by Fraktality** [comment]
Yeah, looks like I was on v2.  Cheers
