### ISSUE TITLE
No normal map for studs on SmoothPlastic 

### ISSUE THREAD

**Issue by David-Cosby** [Roblox/future-is-bright#57]
Aside from the Plastic material, none of the other material have normal maps enabled when studs are applied to the part. I believe this may be intended behavior, SmoothPlastic aside.

Here is a side-by-side comparison on of the two plastic materials.
![image](https://user-images.githubusercontent.com/29415120/28893180-b51b3854-778d-11e7-91af-e8f62ee15980.png)

NOTE : This is also an issue on the official roblox build, which I have been trying to persuade staff to fix for months.

**Comment by zeux** [comment]
I believe studs only show up on SmoothPlastic in Studio Edit mode; regardless; fixing this is outside of the scope of this project.
