### ISSUE TITLE
'Graphics drivers seem to be too old'?

### ISSUE THREAD

**Issue by Reshiram110** [Roblox/future-is-bright#6]
I tried running this custom build of studio to mess around with the prototype lighting system to see what features it had.

But when I attempt to open an empty baseplate or terrain baseplate, I see this in the output:

21:29:51.361 - Your graphics drivers seem to be too old for Roblox to use.

I am using integrated graphics on an intel i3 (Which DO support DirectX11). I am able to run ROBLOX at full quality graphics no problem.

**Comment by DudeWithTheMetalHat** [comment]
I'm having troubles, but not this problem. Maybe try adjusting the compatibility mode in RobloxStudioBeta's properties?

**Comment by Reshiram110** [comment]
That fixed it. It turns out I had the wrong rendering mode configured.

*DERP*
