### ISSUE TITLE
(FeatureRequest) Opal material

### ISSUE THREAD

**Issue by RodjGaming** [Roblox/future-is-bright#60]
(Feature Request Tag needs added)
Opal material would be a great addition to ROBLOX as it would help us with many light fixtures. Opal is basically a material many lighting companies use that allows light to shine through it. I think this on ROBLOX should look like smooth plastic when normal but would allow light to "lighten" it up. Here are some examples:
![image](https://user-images.githubusercontent.com/30380164/29153965-ff818a3e-7d5e-11e7-96ba-4ff86c58d61a.png)
![image](https://user-images.githubusercontent.com/30380164/29154667-09635230-7d64-11e7-9ddb-70912a14b58f.png)
![image](https://user-images.githubusercontent.com/30380164/29154005-35364e08-7d5f-11e7-8b45-23508d24b938.png)
![image](https://user-images.githubusercontent.com/30380164/29154032-6d7f7762-7d5f-11e7-9029-957a6ff4554f.png)
![image](https://user-images.githubusercontent.com/30380164/29154246-175cea66-7d61-11e7-9d95-ee0bbacd0e49.png)
![image](https://user-images.githubusercontent.com/30380164/29154349-e220f9b8-7d61-11e7-984a-69c7025a0909.png)
One other request is for a way of decals to act the same to where it can light up. Ex:
![image](https://user-images.githubusercontent.com/30380164/29154408-74e1b9fe-7d62-11e7-8d26-47e23a5b9305.png)

**Comment by zeux** [comment]
While it might be a good idea to add something like this, adding materials is outside of the scope of this project.
