### ISSUE TITLE
Request: Option to disable Brightness Auto-Adjusting

### ISSUE THREAD

**Issue by ImperatorDuncan** [Roblox/future-is-bright#61]
Often times when fooling around with the new lighting and trying to make the best lighting possible, the auto-adjust feature can easily get in the way. Making dark environments makes even the most obscure differences way too noticeable.

![wallcolorcomparison2](https://user-images.githubusercontent.com/9422747/29233542-08fcad2e-7eb7-11e7-897e-af9048e3126e.png)
_The lights in the room do not change_

It would be nice if there were an option to disable the automatic brightness adjusting.

**Comment by od149** [comment]
I have the same problem when trying to get the best lighting possible, i hope this feature.

**Comment by craftsmashbuild** [comment]
The term you are looking for is HDR, which is enabled on all lighting engines in the build, including the old one they included as a reference. 

I asked Zeuxcg on twitter and he said they plan to add an option to disable HDR in the future: https://twitter.com/craftsmashbuild/status/892500876371279872

**Comment by zeux** [comment]
Fixed in v6 (Lighting.AutoExposure)
