### ISSUE TITLE
New lighting studio crashes when I try to load a place (Didn't use to do this, some other devs I know are having this issue too)

### ISSUE THREAD

**Issue by craftsmashbuild** [Roblox/future-is-bright#63]
**Recently**(as of yesterday, it used to work fine), whenever I try to load a place after launching the new lighting studio, it crashes and gives the error: 

> An unexpected error occurred and Roblox needs to quit! We're sorry!

**This does NOT occur in normal studio, only this build.** 

 Things I have tried:

- Redownloading the latest version
- Using an old version
- Rebooting
- Waiting
- Deleting the Roblox folder in %LocalAppData% and reinstalling Roblox

Other developers I know also say they are suddenly having this issue, I presume it is a Roblox problem.

Just incase it might help, PC specs:
```
Intel core i7 6700
Windows 10 (Up to date)
Nvida Geforce GTX 1060 
16gb DDR4 RAM
Plenty of SSD & HDD space 
```

My guess is this may be related to a Roblox sided update that is incompatible with the latest build of the lighting studio?

**Comment by lblazikenn** [comment]
Turn off your internet then get in a place, it should work.
But my theory is it's trying to force update studio but cant, therefore crashing.

**Comment by lblazikenn** [comment]
also got this method from someone else^^^^

**Comment by craftsmashbuild** [comment]
It works, thanks! I do want to find a more permanent solution though.
