### ISSUE TITLE
No unions are rendering, any way to fix?

### ISSUE THREAD

**Issue by lblazikenn** [Roblox/future-is-bright#64]
The unions in my map dont render, I would love a solution.

**Comment by Deathtouch43** [comment]
if your using the internet method I suggest looking for a way to make a lag switch aka turn off and on your internet really fast. On windows you can do something like "ipconfig /release" then open the place and as soon as the loading bar hits or passes 71% do "ipconfig /renew" which will instantly re-connect you and the unions should load if done fast enough

**Comment by lblazikenn** [comment]
Alright let me try this real quick.

**Comment by zeux** [comment]
The crash is fixed in v4 so this should be fixed as well I believe.
