### ISSUE TITLE
[feature] Add "Static" boolean property to BasePart and Light instances for performance boost

### ISSUE THREAD

**Issue by Knightshade** [Roblox/future-is-bright#65]
If set to true, any property change or method that changes the render based properties would fail with "Cannot modify static geometry". This would allow static items to pre-bake a light map to allegedly allow a performance boost by storing it in its own vertex buffer.

**Comment by zeux** [comment]
We will never use any sort of pre-baking. We currently do some amount of automatic optimizations/caching (particularly for ShadowMap technique) for parts that aren't moving or otherwise changing, and I expect to do even more of that.
