### ISSUE TITLE
GPU Cascaded Flickering

### ISSUE THREAD

**Issue by Kolinchkov** [Roblox/future-is-bright#67]
The shadows and lights seem to flicker as one would move about and, this is very noticeable viewing objects at a distance (GPUCascaded):
![b8ebfdd0a11437cbf71c694eed8db7cb](https://user-images.githubusercontent.com/30379637/29548034-ce06f306-86cb-11e7-893a-1fc1f97ad7d5.png)
![7af57d393d9380f09e12814d2c629e31](https://user-images.githubusercontent.com/30379637/29548035-d127ed06-86cb-11e7-97c6-9c8c7a461a3f.png)

This appears in certain instances on Shadowmap (now note, I can understand such a reaction since the part representing the ocean is quite a large mesh - I cannot recall, but this may also happen at other times in spite the lack of such sizeable meshes):
![b0b3c55b8cef4ac03c8f1f22dcec4e52](https://user-images.githubusercontent.com/30379637/29548151-a13b472c-86cc-11e7-9855-479f6983215a.png)

**Comment by zeux** [comment]
GPU cascaded is no longer supported, so I'll close this.
