### ISSUE TITLE
Weird "big black pixel" artifacts and other lighting glitches happening in my game

### ISSUE THREAD

**Issue by RodjGaming** [Roblox/future-is-bright#7]
When I tested out one of my Groups alleys and tested it in the new lighting, there was so many weird glitches happening to the lighting in both VoxelGPUCascaded and ShadowMap. In VoxelCPU it is normal and runs perfectly fine. One of them was that the normal "white" lighting above the lanes wasn't lighting up but the black lights show up fine. Here is a video of the glitches I was encountering:  https://www.youtube.com/watch?v=zOCIVgon4F4

**Comment by RodjGaming** [comment]
Specs:
Windows 10
Intel Core i3-6100 CPU @ 3.70GHz
8.0 GB RAM

**Comment by RodjGaming** [comment]
At the bottom is a repro of a place that uses the same disco lights causing the bug. Another bug I encountered is that whenever I get close to it, the whole place gets dark and when I back away from it, it brightens back up slowly, here is a video of it: https://www.youtube.com/watch?v=So4gXCBnMzk

[LightGlitchRepro.zip](https://github.com/Roblox/future-is-bright/files/1168363/LightGlitchRepro.zip)

**Comment by zeux** [comment]
@RodjGaming Your level appears to have Brightness set to +inf on all lights which seems like the problem here. I'll add some clamping to prevent this in the future.

**Comment by zeux** [comment]
Will be fixed in v3

**Comment by RodjGaming** [comment]
@zeux I had to have the brightness set up high on them when it was on VoxelCPU in order for them to be noticeable for my use.
