### ISSUE TITLE
ParticleEmitter has weird pixel wave (LightEmission)

### ISSUE THREAD

**Issue by Sparkypen7** [Roblox/future-is-bright#70]
https://i.gyazo.com/7f30a074ebac8e2421c89376c5ccda0b.mp4

Not sure how to describe it.

Also, this is on ShadowMap, VoxelCPU, and VoxelGPUCascaded. The LightEmission of the particle is 5, setting it 0 will make this bug go away.

**Comment by craftsmashbuild** [comment]
This has to do with the light emission of the particles, I thought Zeuxcg fixed it in the latest version but I guess not.

**Comment by tsbuilderboy** [comment]
Well,I think I see the problem. LightEmission is meant to be a number between 0 and 1. It uses addition, so if you were to set it to 5 and the particle was just a pure red square (1, 0, 0), and it was against a cyan sky (0, 1, 1), the result would be 1 * 5 + 0, 0 * 5 + 1, 0 * 5 + 1, or 5, 0, 0. ROBLOX tends to react to Color3 values over 1 by subtracting from all 3 values until all of them are below 1, resulting in that demon you just saw there.

**Comment by zeux** [comment]
I don't think this should happen anymore since we are using a different HDR representation. And yeah LightEmission is supposed to be between 0 and 1...
