### ISSUE TITLE
Request: Option to manually adjust shadowmap resolution (and possibly LOD)

### ISSUE THREAD

**Issue by craftsmashbuild** [Roblox/future-is-bright#72]
I'd like to see an option to manually adjust shadowmap resolution (and possibly LOD). I'm sure others would too. Some users with higher end computers (like me) would like to be able to experience Shadowmap at higher quality, and I think a local option for this would be neat.

**Comment by AshCraft1337** [comment]
bruh wtf you wanna see shadow map in higher quality while im out here with a low end pc begging for a lower quality shadowmap so i dont have to lag while adding lights to my game smh

**Comment by craftsmashbuild** [comment]
@AshCraft1337 **"Option"** **"manually adjust"**

**Comment by Sparkypen7** [comment]
Having a localized configuration of lighting will give players with a high-end PC an advantage in contrast to players with a lower-end PC.

**Comment by craftsmashbuild** [comment]
@Sparkypen7 By localized I hope you mean as per client settings instead of game settings. That way for instance if the settings are in Studio (File>Settings>Render) like most are, you could set it high on a high end Machine but not have to touch it on a low end machine

**Comment by zeux** [comment]
We're trying to match shadow quality between various light sources automatically; we don't have immediate plans to allow adjusting that manually. This may change in the future but for now I'm closing this.
