### ISSUE TITLE
Bug: Stuttering & screentearing on baseplate after new homepage update (high end PC)

### ISSUE THREAD

**Issue by craftsmashbuild** [Roblox/future-is-bright#73]
Specs:
i7 6700
GTX 1060 (yes Roblox is using the dedicated GPU)
16gb DDR4 RAM

**Issue:**

So basically ever since the new startpage update this studio build has been pretty stuttery and laggy, even on a baseplate with a high end machine. The issue seems to be fixed in the normal build of Roblox but not this version.

**Comment by zeux** [comment]
Fixed in v6.
