### ISSUE TITLE
Bugs with v6:

### ISSUE THREAD

**Issue by craftsmashbuild** [Roblox/future-is-bright#74]
- VoxelGPU lighting crashes on a high end PC in detailed places
- VoxelGPU lighting is very dark and looks off 
![image](https://user-images.githubusercontent.com/19627847/31524667-04538c40-af70-11e7-9327-30123af0656b.png)

**Comment by zeux** [comment]
The dark splotches should be fixed in v7. I haven't seen it crash; if this is reproducible and still happens in v7 please post a separate bug with a repro place.
