### ISSUE TITLE
VoxelGPUCascaded Crashing issue on v6 and v7 (video included)

### ISSUE THREAD

**Issue by craftsmashbuild** [Roblox/future-is-bright#75]
Although I mainly use Shadowmap, I decided to try VoxelGPUCascaded on one of the places that I frequently try it on. Normally it works (although slow).

In v6+ I found a crashing bug, studio doesn't freeze when I change the lighting mode but actually crashes.

Video:
https://twitter.com/craftsmashbuild/status/918930741169233920

I'm not entirely sure what's causing the issue so I don't know how to reproduce other then sending a copy of the place I'm using.

**Comment by zeux** [comment]
I think this happens in night time scenes where there's no actual sun shadow to cast, and the new optimized code forgets to handle this case.

**Comment by zeux** [comment]
This should be fixed in v8, can you verify?

**Comment by craftsmashbuild** [comment]
@zeux Yes I can confirm it's fixed, thanks!
