### ISSUE TITLE
roblox.github.io/future-is-bright not updated to v8

### ISSUE THREAD

**Issue by ImperatorDuncan** [Roblox/future-is-bright#76]
The download message still displays v5, and downloads v5
_"Download (.zip, ~120 MB); updated 8/22/2017 (v5)"_

[See here](https://roblox.github.io/future-is-bright/)

**Comment by Knightshade** [comment]
??
Version 8 is right there in the releases tab.

**Comment by craftsmashbuild** [comment]
^

**Comment by zeux** [comment]
Updated to v9, thanks!
