### ISSUE TITLE
CRITICAL: Studio crashes when saving or pressing play, didn't do this two days ago

### ISSUE THREAD

**Issue by craftsmashbuild** [Roblox/future-is-bright#77]
How to reproduce:

Open v8, then either save or press play, if it is already saved as a file ctrl is will instantly crash, if it asks where it save to it gives you a dialog to select the save location, then crashes when you press enter.

When it crashes, a dialog pops up saying:
"An unexpected error has occurred and Roblox needs to quit. We're sorry!"

Also @­tripledomo on twitter confirms this is happening to him also

**Comment by zeux** [comment]
v9 should fix this, can you confirm?

**Comment by craftsmashbuild** [comment]
@zeux Solved, thanks!
