### ISSUE TITLE
I can't publish my game using future is bright! (SOLVED BY buoyantair! THANK YOU!)

### ISSUE THREAD

**Issue by ckchoudek** [Roblox/future-is-bright#79]
Why can't you publish using future is bright?

**Comment by AshCraft1337** [comment]
why would you want to publish a game using future is bright

**Comment by buoyantair** [comment]
@ckchoudek  Future is bright is not production ready!! It's only for prototyping and as a testing ground for the new Roblox rendering engine. So get over it!

**Comment by Hatman42** [comment]
Future is Bright is experimental. It is for testing purposes.

**Comment by buoyantair** [comment]
Someone close this =3

**Comment by craftsmashbuild** [comment]
Whenever I try it, it works, it's compatible with current Roblox from my experience.

**Comment by ckchoudek** [comment]
Thanks! @buoyantair

**Comment by buoyantair** [comment]
@ckchoudek o.e

**Comment by buoyantair** [comment]
@ckchoudek o.e

**Comment by craftsmashbuild** [comment]
­
