### ISSUE TITLE
Certain Map always crashes on ShadowMap

### ISSUE THREAD

**Issue by LouieK22** [Roblox/future-is-bright#8]
I was digging through old place files to try out this. This map has crashed no matter what when switching to ShadowMap. Myself and a friend both tested. This should be unrelated to #2 as we both are on Intel CPUs. Place file attached.
[PBSTTZ.zip](https://github.com/Roblox/future-is-bright/files/1167813/PBSTTZ.zip)

My specs: 
Windows 10 Home, Intel Core i7, 8Gb RAM, Nvidia 960M
His specs:
i5 with 6 GB RAM & intel HD 4000, 8Gb RAM

**Comment by iiTouge** [comment]
ill try it

**Comment by iiTouge** [comment]
I guess there may be some things that trigger it to crash it crashed for me

**Comment by Reshiram110** [comment]
I crash when I try to use shadowmap on the western map.

**Comment by LouieK22** [comment]
@Reshiram110 Do you have an AMD CPU?

**Comment by Reshiram110** [comment]
Windows 7 64 bit

CPU is an Intel i3

**Comment by LouieK22** [comment]
Do other maps work fine?

**Comment by iiTouge** [comment]
Imma try western, that was the on in the preview.

**Comment by Reshiram110** [comment]
Let me test it on other maps.

**Comment by iiTouge** [comment]
aight

**Comment by iiTouge** [comment]
I didnt have probs with the western lighting...

**Comment by Reshiram110** [comment]
I crash with shadowmapping plain and simple.

**Comment by LouieK22** [comment]
Can you create a new issue for this, just list your specs and the maps that don't work

**Comment by Reshiram110** [comment]
k.

**Comment by Knightshade** [comment]
Crashes for me too when trying to set it

**Comment by hunte922** [comment]
You need to turn on GlobalShadows before enabling ShadowMap.

**Comment by LouieK22** [comment]
Looks fixed, closing

**Comment by hunte922** [comment]
The bug isn't fixed, I just found a workaround.

**Comment by zeux** [comment]
The crash will be fixed in the upcoming v3 build (there's still weirdness with GlobalShadows=false but that's separate and there's a bug for it).
