### ISSUE TITLE
When will this be available for Mac/OS

### ISSUE THREAD

**Issue by Stxel** [Roblox/future-is-bright#82]
I am wondering as I am a user of the following system, and you said one would be done like **months** ago.

**Comment by craftsmashbuild** [comment]
~~hopefully never since mac is inferior to pc /s~~

So from what I know the goal is to develop a good lighting technology, the focus at the moment from what I know isn't performance or platform availability.

**Comment by zeux** [comment]
This is a duplicate of #3 anyway, so closing this - please refer to #3 for macOS updates (which should happen momentarily...).
