### ISSUE TITLE
neon does not have any light influence

### ISSUE THREAD

**Issue by BronzedMocha** [Roblox/future-is-bright#83]
neon should have some sort of control on its glow, as well as light influence, along with control with how much light is emitted. 
![screenshot_202](https://user-images.githubusercontent.com/34043971/33292011-5c2f33e2-d38d-11e7-9f8c-dda1c2c9b6e2.png)

**Comment by tsbuilderboy** [comment]
...the whole purpose of Neon is that it isn't influenced by light. ...and you can change the glow amount by darkening the BrickColor, for example changing it from 255, 0, 0 to 63, 0, 0.

**Comment by zeux** [comment]
Yeah - you can adjust neon influence by adjusting the color. We also will probably tweak the neon effect in these builds somewhat since it's pretty different, but we don't have plans to expose extra controls as part of this project.
