### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by Stxel** [Roblox/future-is-bright#86]
I receive a black screen, to where I cant view anything but the toolbar, etc.

-- Running Mac/OS Version.

**Comment by IDontLikeSand** [comment]
Me too, I am also on a Mac (Desktop).

**Comment by IDontLikeSand** [comment]
I think I found the problem, I think we may have to download Metal (application).
Though I haven't tested that yet.

**Comment by Knightshade** [comment]
It does say metal is required on the changelog

**Comment by zeux** [comment]
Unfortunately, the builds require Metal support and we don't have plans to support OpenGL. Metal requires a new OSX (10.11 or above), and a compatible Mac - please refer to https://support.apple.com/en-us/HT205073
