### ISSUE TITLE
The "Projects" screen freezes.

### ISSUE THREAD

**Issue by HalfaMale** [Roblox/future-is-bright#89]
Trying to load a new map, or an old save, freezes the Projects tab/Page on the screen, the  map does load. (I think.) But the tabs are on the way.
![published as baseplate - roblox studio 13 1 2018 17 26 26](https://user-images.githubusercontent.com/35401819/34907426-f52bdbc2-f886-11e7-8735-c4c1caae8f80.png)
Like so.

**Comment by Veepler** [comment]
Been having the same issue, i'm surprised this hasn't been noticed yet.

**Comment by zeux** [comment]
This most likely means that your system doesn't support FIB; please check the Output window for more details. Note that you have to have a DirectX 10 class GPU on Windows and a GPU that supports Metal and OSX 10.11+ on Mac.
