### ISSUE TITLE
Fog is way too bright

### ISSUE THREAD

**Issue by filiptibell** [Roblox/future-is-bright#90]
Using any of the current modes, the fog is really bright and white most of the time, even when using very dark or solid color fog colors

**Comment by tsbuilderboy** [comment]
That's because of the AE. Turn off Auto-Exposure.

**Comment by Thealphascript** [comment]
Well i already tried that and it still was visible.I could see grey just covering the darkness.

**Comment by zeux** [comment]
Fog should function reasonably well on v16 now.
