### ISSUE TITLE
Hybrid mode is now the only available mode?

### ISSUE THREAD

**Issue by DamnMerc** [Roblox/future-is-bright#91]
Can't seem to understand this, as the rendering page does not have this at all. 'FutureIsBright is now a setting in Studio Rendering settings'

**Comment by zeux** [comment]
In the previous builds, you could select the lighting engine via Lighting property; starting with v12, you need to enable this Studio setting instead:

![image](https://user-images.githubusercontent.com/1106629/37778027-2b82ff4e-2da6-11e8-8d9f-d1e741f1db56.png)

If you don't have the setting you must be using the wrong build.

**Comment by DamnMerc** [comment]
I'm using the latest version of regular studio, and the only available download for FiB studio (v11). I don't see the option on either.
Regular:
![image](https://user-images.githubusercontent.com/8603387/37790962-523e16ae-2dde-11e8-87d0-42a8e24eaa40.png)
FiB Studio:
![image](https://user-images.githubusercontent.com/8603387/37791001-6d88edee-2dde-11e8-8103-2148f534c9ea.png)
Is there an update somewhere I missed..?

**Comment by DamnMerc** [comment]
The website still shows the v11 download, did you forget to update it?

**Comment by RodjGaming** [comment]
Version 12 is here: https://github.com/Roblox/future-is-bright/releases
