### ISSUE TITLE
terrain

### ISSUE THREAD

**Issue by slyslasher24** [Roblox/future-is-bright#93]
The new lighting is not displaying any terrain whatsoever in studio, and when I try to add terrain studio crashes.

**Comment by zeux** [comment]
Is this on Windows or Mac? Does it still happen with v13?

**Comment by slyslasher24** [comment]
Windows, not sure haven't tried it, but it was on the most recent version
when I made the post.

I think it was just because of team create, though, on my offline files it
worked fine.

**Comment by zeux** [comment]
Ah - ok. We had Team Create broken in one of the earlier builds I think; v13 appears to work so I'll close this.
