### ISSUE TITLE
Strange Lines appearing on large objects from a far distance

### ISSUE THREAD

**Issue by EXYZED** [Roblox/future-is-bright#96]
Unsure if this is normal behavior but I'd thought i'd mention it anyway.
- Seems to be occurring towards corners of **large** parts
- In result, several beams of shadows form and fade out.

![1](https://user-images.githubusercontent.com/18582414/38299721-cc339d26-37f2-11e8-818f-d2e778063b83.PNG)
![capture](https://user-images.githubusercontent.com/18582414/38299742-d513faf8-37f2-11e8-8a47-2e90f17598cb.PNG)

**Comment by zeux** [comment]
Can you check if this still happens on v13? We reworked some shadow code that has to do with this. If it does, mind uploading a test place where this happens?

**Comment by zeux** [comment]
@DamnMerc I don't think this is related - can you please file a separate issue for this, with reproduction steps and your hardware/OS?
