### ISSUE TITLE
Modes not appearing?

### ISSUE THREAD

**Issue by Thealphascript** [Roblox/future-is-bright#97]
Every time I open it, it does not show the different modes but it does work in ways yeah the realistic shadows and everything, and I did look on the experimental of course.Did it not download everything somehow??

**Comment by DamnMerc** [comment]
It's called Hybrid. It's using ShadowMap and current ROBLOX lighting simultaneously.

**Comment by Thealphascript** [comment]
@DamnMerc then what should I do to get the previous??

**Comment by DamnMerc** [comment]
@Thealphascript Check the previous releases.

**Comment by DamnMerc** [comment]
Whatever your space is occupied with, is your own issue. I can only tell you to get the previous version for the modes.

**Comment by zeux** [comment]
https://roblox.github.io/future-is-bright/ has been updated to explain the new toggle mechanism.
